include: package:flutter_lints/flutter.yaml

analyzer:
  # plugins:
  #   - custom_lint  # analyzer_plugin 버전 충돌로 임시 비활성화
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - avoid_print
