import 'dart:convert';

/// 가상 서버 번들 레시피 데이터 (25가지 한국 대표 요리).
///
/// FastAPI 백엔드 응답과 동일한 JSON 스키마 (Recipe.fromJson 호환).
/// 실 백엔드 구축 시 이 데이터를 서버 DB로 마이그레이션한다.
class MockRecipeData {
  MockRecipeData._();

  /// 요리명 정확 일치 조회. 없으면 null (→ AI 폴백).
  ///
  /// const Map의 중첩 타입(Map<String, Object>)을 Recipe.fromJson이 요구하는
  /// Map<String, dynamic>으로 정규화하기 위해 JSON 라운드트립을 적용한다.
  static Map<String, dynamic>? findByName(String dishName) {
    final raw = _kRecipes[dishName];
    if (raw == null) return null;
    return json.decode(json.encode(raw)) as Map<String, dynamic>;
  }

  static const Map<String, Map<String, dynamic>> _kRecipes = {
    // ─────────────────────────────────────────────────────────────
    // 국물 · 찌개
    // ─────────────────────────────────────────────────────────────
    '된장찌개': {
      'id': 'srv_doenjang_jjigae_v1',
      'title': '된장찌개',
      'description': '집에서 뚝딱, 깊고 구수한 맛',
      'recipeType': 'soup',
      'servings': 2,
      'cookingTimeMinutes': 20,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '된장', 'amount': '2.5', 'unit': '큰술', 'isOptional': false},
        {'name': '두부', 'amount': '150', 'unit': 'g', 'isOptional': false},
        {'name': '애호박', 'amount': '1/3', 'unit': '개', 'isOptional': false},
        {'name': '대파', 'amount': '1/2', 'unit': '대', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '물', 'amount': '500', 'unit': 'ml', 'isOptional': false},
        {'name': '청양고추', 'amount': '1', 'unit': '개', 'isOptional': true},
        {'name': '고추장', 'amount': '0.5', 'unit': '큰술', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '두부는 2cm 깍둑, 애호박은 반달 모양으로 썰고, 대파는 어슷 썰기, 마늘을 다진다.', 'durationSeconds': 180, 'tip': '두부는 키친타월로 물기를 제거하면 더 탱탱하다'},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 물 500ml를 붓고 센 불에 올려 끓인다.', 'durationSeconds': 120},
        {'stepNumber': 3, 'phase': 'base', 'description': '물이 끓으면 된장을 체에 걸러 넣고 다진 마늘을 추가한다.', 'durationSeconds': 60, 'tip': '체로 거르면 국물이 맑고 잡내가 줄어든다'},
        {'stepNumber': 4, 'phase': 'main', 'description': '애호박과 두부를 넣고 중불에서 5분 끓인다.', 'durationSeconds': 300},
        {'stepNumber': 5, 'phase': 'season', 'description': '대파, 청양고추를 넣고 간을 본다. 싱거우면 된장을 소량 추가.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '불을 끄기 30초 전 참기름 한 방울을 두른다.', 'durationSeconds': 30, 'tip': '참기름은 불을 끄기 직전에 넣어야 향이 살아난다'},
        {'stepNumber': 7, 'phase': 'plate', 'description': '뚝배기 또는 그릇에 담아 밥과 함께 낸다.'},
      ],
      'tags': ['한식', '찌개', '된장', '두부', '든든'],
      'flavorProfile': {'umami': 5, 'sweet': 1, 'sour': 0, 'salty': 3, 'spicy': 1},
      'scienceNote': '된장의 구수함은 콩 단백질이 메주 발효 과정에서 분해된 글루탐산(umami)에서 비롯된다.',
      'sources': [],
    },

    '김치찌개': {
      'id': 'srv_kimchi_jjigae_v1',
      'title': '김치찌개',
      'description': '얼큰하고 시원한 국물 한 냄비',
      'recipeType': 'soup',
      'servings': 2,
      'cookingTimeMinutes': 25,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '묵은 김치', 'amount': '200', 'unit': 'g', 'isOptional': false},
        {'name': '돼지고기 (앞다리살)', 'amount': '150', 'unit': 'g', 'isOptional': false},
        {'name': '두부', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '대파', 'amount': '1/2', 'unit': '대', 'isOptional': false},
        {'name': '고춧가루', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '물', 'amount': '400', 'unit': 'ml', 'isOptional': false},
        {'name': '김치 국물', 'amount': '3', 'unit': '큰술', 'isOptional': true},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '김치는 큼직하게, 두부는 사방 2cm, 돼지고기는 한입 크기로 썰고, 대파는 어슷 썬다.', 'durationSeconds': 180},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 참기름을 두르고 중불에 올린다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '돼지고기를 넣고 겉면이 하얗게 변할 때까지 볶은 뒤 김치를 넣어 함께 볶는다.', 'durationSeconds': 180, 'tip': '고기를 먼저 볶으면 잡내가 줄어든다'},
        {'stepNumber': 4, 'phase': 'main', 'description': '물과 김치 국물을 넣고 고춧가루, 다진 마늘을 추가한 뒤 센 불에서 10분 끓인다.', 'durationSeconds': 600},
        {'stepNumber': 5, 'phase': 'season', 'description': '두부를 넣고 5분 더 끓이며 간을 본다. 싱거우면 김치 국물 추가.', 'durationSeconds': 300},
        {'stepNumber': 6, 'phase': 'finish', 'description': '대파를 넣고 불을 끈다.', 'durationSeconds': 30},
        {'stepNumber': 7, 'phase': 'plate', 'description': '뚝배기에 담아 펄펄 끓인 채로 밥상에 낸다.', 'tip': '끓는 상태로 내면 더 맛있다'},
      ],
      'tags': ['한식', '찌개', '김치', '돼지고기', '얼큰'],
      'flavorProfile': {'umami': 4, 'sweet': 1, 'sour': 2, 'salty': 3, 'spicy': 4},
      'scienceNote': '묵은 김치는 유산균 발효가 깊어져 신맛과 감칠맛이 강해지고, 지방과 만나면 더 풍부한 국물맛을 낸다.',
      'sources': [],
    },

    '순두부찌개': {
      'id': 'srv_sundubu_jjigae_v1',
      'title': '순두부찌개',
      'description': '부드럽고 칼칼한 순두부',
      'recipeType': 'soup',
      'servings': 2,
      'cookingTimeMinutes': 20,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '순두부', 'amount': '1', 'unit': '팩 (300g)', 'isOptional': false},
        {'name': '바지락', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '고춧가루', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '국간장', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '달걀', 'amount': '2', 'unit': '개', 'isOptional': false},
        {'name': '대파', 'amount': '1/3', 'unit': '대', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '물', 'amount': '300', 'unit': 'ml', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '바지락은 소금물에 30분 해감하고, 대파는 어슷 썬다.', 'durationSeconds': 1800, 'tip': '바지락을 미리 해감해 두면 조리 시간이 단축된다'},
        {'stepNumber': 2, 'phase': 'heat', 'description': '뚝배기에 참기름을 두르고 고춧가루를 넣어 중불에서 30초 볶아 기름을 낸다.', 'durationSeconds': 90, 'tip': '고춧가루를 기름에 볶으면 색과 향이 풍부해진다'},
        {'stepNumber': 3, 'phase': 'base', 'description': '다진 마늘과 바지락을 넣고 1분 볶다가 물을 붓는다.', 'durationSeconds': 120},
        {'stepNumber': 4, 'phase': 'main', 'description': '끓어오르면 순두부를 큰 숟가락으로 떠 넣고 국간장으로 간한다.', 'durationSeconds': 180},
        {'stepNumber': 5, 'phase': 'season', 'description': '간을 보고 부족하면 국간장 추가. 대파를 넣는다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '달걀을 깨 넣고 뚜껑을 덮어 1분 익힌다.', 'durationSeconds': 60, 'tip': '달걀 노른자를 반숙으로 유지하면 더 맛있다'},
        {'stepNumber': 7, 'phase': 'plate', 'description': '뚝배기 그대로 밥상에 낸다.'},
      ],
      'tags': ['한식', '찌개', '순두부', '칼칼', '든든'],
      'flavorProfile': {'umami': 4, 'sweet': 0, 'sour': 0, 'salty': 3, 'spicy': 4},
      'sources': [],
    },

    '미역국': {
      'id': 'srv_miyeok_guk_v1',
      'title': '미역국',
      'description': '담백하고 시원한 생일국',
      'recipeType': 'soup',
      'servings': 2,
      'cookingTimeMinutes': 30,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '건미역', 'amount': '10', 'unit': 'g', 'isOptional': false},
        {'name': '소고기 (양지)', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '국간장', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '물', 'amount': '700', 'unit': 'ml', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '건미역은 찬물에 15분 불려 물기를 꼭 짜고 먹기 좋게 썬다. 소고기는 한입 크기로 썬다.', 'durationSeconds': 900, 'tip': '미역은 불리면 5~7배 부피가 늘어난다'},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 참기름을 두르고 중불에 올린다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '소고기를 넣고 겉면이 갈색이 될 때까지 볶은 뒤 미역을 넣어 함께 1분 더 볶는다.', 'durationSeconds': 180, 'tip': '참기름에 볶으면 미역의 비린내가 잡힌다'},
        {'stepNumber': 4, 'phase': 'main', 'description': '물 700ml를 넣고 센 불에서 끓인다. 끓어오르면 거품을 걷어낸다.', 'durationSeconds': 300},
        {'stepNumber': 5, 'phase': 'season', 'description': '국간장과 다진 마늘을 넣고 중불에서 10분 더 끓인다.', 'durationSeconds': 600},
        {'stepNumber': 6, 'phase': 'finish', 'description': '간을 보고 국간장으로 조절한다.', 'durationSeconds': 60},
        {'stepNumber': 7, 'phase': 'plate', 'description': '그릇에 담아 밥과 함께 낸다.'},
      ],
      'tags': ['한식', '국', '미역', '소고기', '생일'],
      'flavorProfile': {'umami': 4, 'sweet': 0, 'sour': 0, 'salty': 2, 'spicy': 0},
      'scienceNote': '미역의 끈끈한 질감은 알긴산(alginic acid) 성분으로, 콜레스테롤 흡착 및 배출에 도움을 준다.',
      'sources': [],
    },

    '콩나물국': {
      'id': 'srv_kongnamul_guk_v1',
      'title': '콩나물국',
      'description': '시원하고 깔끔한 숙취해소',
      'recipeType': 'soup',
      'servings': 2,
      'cookingTimeMinutes': 15,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '콩나물', 'amount': '200', 'unit': 'g', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '대파', 'amount': '1/3', 'unit': '대', 'isOptional': false},
        {'name': '국간장', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '물', 'amount': '500', 'unit': 'ml', 'isOptional': false},
        {'name': '고춧가루', 'amount': '0.5', 'unit': '작은술', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '콩나물을 씻어 체에 밭쳐 물기를 뺀다. 대파는 어슷 썬다.', 'durationSeconds': 120},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 물을 넣고 센 불에 올린다.', 'durationSeconds': 120},
        {'stepNumber': 3, 'phase': 'base', 'description': '물이 끓으면 콩나물을 넣고 뚜껑을 닫는다.', 'durationSeconds': 60, 'tip': '뚜껑을 열지 않으면 비린내가 나지 않는다'},
        {'stepNumber': 4, 'phase': 'main', 'description': '5분간 뚜껑을 열지 않고 끓인다.', 'durationSeconds': 300},
        {'stepNumber': 5, 'phase': 'season', 'description': '다진 마늘, 국간장을 넣고 1분 더 끓인다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '대파와 고춧가루를 넣고 불을 끈다.', 'durationSeconds': 30},
        {'stepNumber': 7, 'phase': 'plate', 'description': '뜨거운 국을 그릇에 담아 낸다.'},
      ],
      'tags': ['한식', '국', '콩나물', '해장', '간단'],
      'flavorProfile': {'umami': 2, 'sweet': 0, 'sour': 0, 'salty': 2, 'spicy': 1},
      'sources': [],
    },

    '계란국': {
      'id': 'srv_gyeran_guk_v1',
      'title': '계란국',
      'description': '5분 만에 뚝딱 간단국',
      'recipeType': 'soup',
      'servings': 2,
      'cookingTimeMinutes': 5,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '달걀', 'amount': '3', 'unit': '개', 'isOptional': false},
        {'name': '국간장', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '0.5', 'unit': '작은술', 'isOptional': false},
        {'name': '대파', 'amount': '1/3', 'unit': '대', 'isOptional': false},
        {'name': '물', 'amount': '500', 'unit': 'ml', 'isOptional': false},
        {'name': '참기름', 'amount': '0.5', 'unit': '작은술', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '달걀을 볼에 풀어 젓가락으로 고루 섞는다. 대파는 어슷 썬다.', 'durationSeconds': 60},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 물을 넣고 센 불에 올려 끓인다.', 'durationSeconds': 120},
        {'stepNumber': 3, 'phase': 'base', 'description': '국간장과 다진 마늘을 넣고 1분 더 끓인다.', 'durationSeconds': 60},
        {'stepNumber': 4, 'phase': 'main', 'description': '달걀물을 가는 줄기로 빙 돌려가며 붓고 젓가락으로 한번 휙 젓는다.', 'durationSeconds': 30, 'tip': '달걀물을 한꺼번에 부으면 덩어리지니 가늘게 넣는다'},
        {'stepNumber': 5, 'phase': 'season', 'description': '간을 보고 부족하면 소금 또는 국간장 추가.', 'durationSeconds': 30},
        {'stepNumber': 6, 'phase': 'finish', 'description': '대파를 넣고 참기름을 두른 뒤 불을 끈다.', 'durationSeconds': 20},
        {'stepNumber': 7, 'phase': 'plate', 'description': '그릇에 담아 낸다.'},
      ],
      'tags': ['한식', '국', '달걀', '간단', '빠른요리'],
      'flavorProfile': {'umami': 3, 'sweet': 0, 'sour': 0, 'salty': 2, 'spicy': 0},
      'sources': [],
    },

    '닭볶음탕': {
      'id': 'srv_dakbokkeum_tang_v1',
      'title': '닭볶음탕',
      'description': '칼칼하게 끓인 닭도리탕',
      'recipeType': 'soup',
      'servings': 2,
      'cookingTimeMinutes': 45,
      'difficulty': 'medium',
      'ingredients': [
        {'name': '닭 (토막)', 'amount': '500', 'unit': 'g', 'isOptional': false},
        {'name': '감자', 'amount': '1', 'unit': '개', 'isOptional': false},
        {'name': '당근', 'amount': '1/2', 'unit': '개', 'isOptional': false},
        {'name': '양파', 'amount': '1/2', 'unit': '개', 'isOptional': false},
        {'name': '고춧가루', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '간장', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '물', 'amount': '300', 'unit': 'ml', 'isOptional': false},
        {'name': '대파', 'amount': '1', 'unit': '대', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '닭은 찬물에 20분 담가 핏물 제거. 감자·당근은 한입 크기, 양파는 굵게 썬다.', 'durationSeconds': 1200},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 닭을 넣고 물 300ml를 붓고 센 불에 올린다.', 'durationSeconds': 120},
        {'stepNumber': 3, 'phase': 'base', 'description': '끓어오르면 거품을 걷어내고 고춧가루, 간장, 마늘, 설탕을 넣는다.', 'durationSeconds': 120, 'tip': '거품을 잘 걷어야 국물이 맑아진다'},
        {'stepNumber': 4, 'phase': 'main', 'description': '감자, 당근, 양파를 넣고 중불에서 20분 끓인다.', 'durationSeconds': 1200},
        {'stepNumber': 5, 'phase': 'season', 'description': '간을 보고 부족하면 간장 추가. 국물이 자작하게 남아있어야 한다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '대파를 넣고 5분 더 조린다.', 'durationSeconds': 300},
        {'stepNumber': 7, 'phase': 'plate', 'description': '냄비째 또는 깊은 그릇에 담아 밥과 함께 낸다.'},
      ],
      'tags': ['한식', '닭', '조림', '칼칼', '든든'],
      'flavorProfile': {'umami': 4, 'sweet': 2, 'sour': 0, 'salty': 3, 'spicy': 4},
      'sources': [],
    },

    '부대찌개': {
      'id': 'srv_budae_jjigae_v1',
      'title': '부대찌개',
      'description': '소시지 햄 가득 부대찌개',
      'recipeType': 'soup',
      'servings': 2,
      'cookingTimeMinutes': 30,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '스팸 (햄)', 'amount': '150', 'unit': 'g', 'isOptional': false},
        {'name': '비엔나 소시지', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '김치', 'amount': '150', 'unit': 'g', 'isOptional': false},
        {'name': '두부', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '떡국떡', 'amount': '80', 'unit': 'g', 'isOptional': true},
        {'name': '라면 사리', 'amount': '1', 'unit': '개', 'isOptional': true},
        {'name': '고춧가루', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '물', 'amount': '500', 'unit': 'ml', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '햄과 소시지는 먹기 좋게, 두부는 1.5cm 두께로 썰고, 김치는 큼직하게 썬다.', 'durationSeconds': 180},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비(또는 전골 냄비)에 재료를 보기 좋게 분리해 담는다.', 'durationSeconds': 120},
        {'stepNumber': 3, 'phase': 'base', 'description': '고춧가루, 다진 마늘을 가운데 넣고 물을 붓는다.', 'durationSeconds': 60},
        {'stepNumber': 4, 'phase': 'main', 'description': '센 불에서 끓어오를 때까지 가열하고, 중불로 줄여 10분 더 끓인다.', 'durationSeconds': 600},
        {'stepNumber': 5, 'phase': 'season', 'description': '간을 보고 싱거우면 소금이나 라면 스프로 보완한다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '라면 사리를 넣고 2분 더 끓인다.', 'durationSeconds': 120},
        {'stepNumber': 7, 'phase': 'plate', 'description': '냄비째 상에 올려 함께 먹는다.', 'tip': '먹으면서 계속 끓이면 더 맛있다'},
      ],
      'tags': ['한식', '찌개', '햄', '소시지', '얼큰'],
      'flavorProfile': {'umami': 4, 'sweet': 2, 'sour': 1, 'salty': 4, 'spicy': 3},
      'sources': [],
    },

    // ─────────────────────────────────────────────────────────────
    // 주요리 (Main)
    // ─────────────────────────────────────────────────────────────
    '계란볶음밥': {
      'id': 'srv_gyeran_bokkeum_bap_v1',
      'title': '계란볶음밥',
      'description': '냉장고 털어 만드는 볶음밥',
      'recipeType': 'main',
      'servings': 2,
      'cookingTimeMinutes': 10,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '밥', 'amount': '2', 'unit': '공기', 'isOptional': false},
        {'name': '달걀', 'amount': '3', 'unit': '개', 'isOptional': false},
        {'name': '대파', 'amount': '1/3', 'unit': '대', 'isOptional': false},
        {'name': '간장', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '식용유', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '소금', 'amount': '적당량', 'unit': '', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '달걀을 볼에 깨 넣고 소금 한 꼬집과 함께 잘 섞는다. 대파는 송송 썬다.', 'durationSeconds': 60},
        {'stepNumber': 2, 'phase': 'heat', 'description': '팬에 식용유를 두르고 센 불에 올려 충분히 달군다.', 'durationSeconds': 60, 'tip': '팬이 충분히 뜨거워야 밥이 눌어붙지 않는다'},
        {'stepNumber': 3, 'phase': 'base', 'description': '달걀물을 붓고 반숙 상태에서 바로 밥을 넣어 강불에 빠르게 섞는다.', 'durationSeconds': 90, 'tip': '달걀이 완전히 익기 전에 밥을 넣어야 부슬부슬해진다'},
        {'stepNumber': 4, 'phase': 'main', 'description': '주걱으로 밥알을 풀어가며 30초~1분 고루 볶는다.', 'durationSeconds': 60},
        {'stepNumber': 5, 'phase': 'season', 'description': '간장을 팬 가장자리에 둘러 넣고 빠르게 섞는다.', 'durationSeconds': 30, 'tip': '간장을 팬 가장자리에 부으면 고소한 향이 난다'},
        {'stepNumber': 6, 'phase': 'finish', 'description': '불을 끄고 참기름과 대파를 넣어 고루 섞는다.', 'durationSeconds': 20},
        {'stepNumber': 7, 'phase': 'plate', 'description': '그릇에 담고 김치나 단무지와 함께 낸다.'},
      ],
      'tags': ['한식', '볶음밥', '달걀', '간단', '빠른요리'],
      'flavorProfile': {'umami': 3, 'sweet': 0, 'sour': 0, 'salty': 2, 'spicy': 0},
      'sources': [],
    },

    '제육볶음': {
      'id': 'srv_jeyuk_bokkeum_v1',
      'title': '제육볶음',
      'description': '밥 도둑 매콤 돼지볶음',
      'recipeType': 'main',
      'servings': 2,
      'cookingTimeMinutes': 20,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '돼지고기 (앞다리살)', 'amount': '300', 'unit': 'g', 'isOptional': false},
        {'name': '고추장', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '고춧가루', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '간장', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 생강', 'amount': '0.5', 'unit': '작은술', 'isOptional': true},
        {'name': '양파', 'amount': '1/2', 'unit': '개', 'isOptional': false},
        {'name': '대파', 'amount': '1/2', 'unit': '대', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '통깨', 'amount': '1', 'unit': '작은술', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '돼지고기는 얇게 썰고 양파는 채, 대파는 어슷 썬다.', 'durationSeconds': 180},
        {'stepNumber': 2, 'phase': 'heat', 'description': '고추장, 고춧가루, 간장, 설탕, 마늘, 생강을 섞어 양념장을 만든다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '고기에 양념장을 넣고 20분 이상 재운다.', 'durationSeconds': 1200, 'tip': '냉장고에서 30분~1시간 재우면 더 깊은 맛이 난다'},
        {'stepNumber': 4, 'phase': 'main', 'description': '팬에 식용유 없이(고기 기름만으로) 센 불에서 재운 고기를 볶는다.', 'durationSeconds': 240, 'tip': '센 불에서 빠르게 볶아야 육즙이 살아있다'},
        {'stepNumber': 5, 'phase': 'season', 'description': '양파와 대파를 넣고 1분 더 볶아 익힌다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '불을 끄고 참기름, 통깨를 넣어 고루 버무린다.', 'durationSeconds': 20},
        {'stepNumber': 7, 'phase': 'plate', 'description': '밥 위에 올려 상추와 함께 낸다.'},
      ],
      'tags': ['한식', '볶음', '돼지고기', '매콤', '밥도둑'],
      'flavorProfile': {'umami': 4, 'sweet': 2, 'sour': 0, 'salty': 3, 'spicy': 4},
      'scienceNote': '마이야르 반응(Maillard reaction)으로 고기 표면이 갈색이 되며 복잡한 풍미가 생성된다. 센 불이 핵심이다.',
      'sources': [],
    },

    '불고기': {
      'id': 'srv_bulgogi_v1',
      'title': '불고기',
      'description': '달콤한 간장 소고기구이',
      'recipeType': 'main',
      'servings': 2,
      'cookingTimeMinutes': 30,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '소고기 (불고기용)', 'amount': '300', 'unit': 'g', 'isOptional': false},
        {'name': '간장', 'amount': '3', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '배즙', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '후추', 'amount': '약간', 'unit': '', 'isOptional': false},
        {'name': '양파', 'amount': '1/4', 'unit': '개', 'isOptional': false},
        {'name': '대파', 'amount': '1/3', 'unit': '대', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '소고기는 키친타월로 핏물 제거. 양파는 채, 대파는 어슷 썬다.', 'durationSeconds': 120},
        {'stepNumber': 2, 'phase': 'heat', 'description': '간장, 설탕, 배즙, 마늘, 참기름, 후추를 섞어 양념장을 만든다.', 'durationSeconds': 60, 'tip': '배즙은 고기를 연하게 하는 단백질 분해 효소가 들어있다'},
        {'stepNumber': 3, 'phase': 'base', 'description': '고기에 양념장을 넣고 30분 이상 재운다.', 'durationSeconds': 1800},
        {'stepNumber': 4, 'phase': 'main', 'description': '팬을 센 불에 달구고 재운 고기를 넣어 빠르게 볶는다.', 'durationSeconds': 240},
        {'stepNumber': 5, 'phase': 'season', 'description': '양파와 대파를 넣고 1분 더 볶아 간을 본다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '참기름을 한 방울 더 두르고 통깨를 뿌린다.', 'durationSeconds': 20},
        {'stepNumber': 7, 'phase': 'plate', 'description': '상추, 깻잎과 함께 쌈으로 내거나 밥 위에 올려 낸다.'},
      ],
      'tags': ['한식', '소고기', '구이', '달콤', '쌈'],
      'flavorProfile': {'umami': 4, 'sweet': 3, 'sour': 0, 'salty': 3, 'spicy': 0},
      'sources': [],
    },

    '잡채': {
      'id': 'srv_japchae_v1',
      'title': '잡채',
      'description': '당면과 채소의 달달한 조화',
      'recipeType': 'main',
      'servings': 2,
      'cookingTimeMinutes': 40,
      'difficulty': 'medium',
      'ingredients': [
        {'name': '당면', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '소고기 (채)', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '시금치', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '당근', 'amount': '1/4', 'unit': '개', 'isOptional': false},
        {'name': '양파', 'amount': '1/2', 'unit': '개', 'isOptional': false},
        {'name': '표고버섯', 'amount': '3', 'unit': '개', 'isOptional': false},
        {'name': '간장', 'amount': '3', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '참기름', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '통깨', 'amount': '1', 'unit': '작은술', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '당면은 30분 물에 불리고, 채소는 가늘게 채 썰고, 소고기는 간장·설탕·마늘로 10분 재운다.', 'durationSeconds': 1800},
        {'stepNumber': 2, 'phase': 'heat', 'description': '끓는 물에 당면 5분 삶아 체에 밭친다. 시금치도 30초 데쳐 찬물에 헹군다.', 'durationSeconds': 360},
        {'stepNumber': 3, 'phase': 'base', 'description': '팬에 기름을 두르고 당근·양파·버섯을 각각 볶아낸다.', 'durationSeconds': 300, 'tip': '각 재료를 따로 볶으면 제각기 식감이 살아난다'},
        {'stepNumber': 4, 'phase': 'main', 'description': '소고기를 볶고, 삶은 당면을 넣어 간장·설탕으로 양념하며 볶는다.', 'durationSeconds': 240},
        {'stepNumber': 5, 'phase': 'season', 'description': '모든 재료를 합쳐 참기름으로 고루 버무린다.', 'durationSeconds': 120},
        {'stepNumber': 6, 'phase': 'finish', 'description': '간을 보고 부족하면 간장 소량 추가.', 'durationSeconds': 30},
        {'stepNumber': 7, 'phase': 'plate', 'description': '통깨를 뿌려 명절 그릇에 담아 낸다.'},
      ],
      'tags': ['한식', '당면', '명절', '잔치', '채소'],
      'flavorProfile': {'umami': 3, 'sweet': 3, 'sour': 0, 'salty': 3, 'spicy': 0},
      'sources': [],
    },

    '닭갈비': {
      'id': 'srv_dakgalbi_v1',
      'title': '닭갈비',
      'description': '춘천식 매콤달콤 닭볶음',
      'recipeType': 'main',
      'servings': 2,
      'cookingTimeMinutes': 30,
      'difficulty': 'medium',
      'ingredients': [
        {'name': '닭 (뼈 없는 허벅지)', 'amount': '400', 'unit': 'g', 'isOptional': false},
        {'name': '고추장', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '고춧가루', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '간장', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '고구마', 'amount': '1/2', 'unit': '개', 'isOptional': false},
        {'name': '양배추', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '대파', 'amount': '1', 'unit': '대', 'isOptional': false},
        {'name': '떡볶이 떡', 'amount': '80', 'unit': 'g', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '닭은 한입 크기로 잘라 키친타월로 물기 제거. 고구마·양배추는 먹기 좋게 썬다.', 'durationSeconds': 300},
        {'stepNumber': 2, 'phase': 'heat', 'description': '고추장, 고춧가루, 간장, 설탕, 마늘을 섞어 양념장을 만들고 닭에 버무려 30분 재운다.', 'durationSeconds': 1800},
        {'stepNumber': 3, 'phase': 'base', 'description': '넓은 팬에 기름을 두르고 재운 닭을 중강불에서 굽듯 볶는다.', 'durationSeconds': 300},
        {'stepNumber': 4, 'phase': 'main', 'description': '고구마와 떡을 넣고 뚜껑 덮어 5분 익힌다.', 'durationSeconds': 300},
        {'stepNumber': 5, 'phase': 'season', 'description': '양배추와 대파를 넣고 뚜껑 없이 수분을 날리며 볶는다.', 'durationSeconds': 180},
        {'stepNumber': 6, 'phase': 'finish', 'description': '간을 보고 부족하면 고추장 소량 추가. 참기름 한 방울.', 'durationSeconds': 30},
        {'stepNumber': 7, 'phase': 'plate', 'description': '철판이나 냄비째 상에 올려 치즈를 올려도 맛있다.'},
      ],
      'tags': ['한식', '닭고기', '매콤', '춘천', '철판'],
      'flavorProfile': {'umami': 3, 'sweet': 3, 'sour': 0, 'salty': 3, 'spicy': 4},
      'sources': [],
    },

    '참치김치볶음밥': {
      'id': 'srv_chamchi_kimchi_bap_v1',
      'title': '참치김치볶음밥',
      'description': '참치캔으로 만드는 간편식',
      'recipeType': 'main',
      'servings': 2,
      'cookingTimeMinutes': 15,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '밥', 'amount': '2', 'unit': '공기', 'isOptional': false},
        {'name': '참치캔', 'amount': '1', 'unit': '캔 (150g)', 'isOptional': false},
        {'name': '김치', 'amount': '150', 'unit': 'g', 'isOptional': false},
        {'name': '달걀', 'amount': '2', 'unit': '개', 'isOptional': false},
        {'name': '대파', 'amount': '1/4', 'unit': '대', 'isOptional': false},
        {'name': '고추장', 'amount': '1', 'unit': '큰술', 'isOptional': true},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '통깨', 'amount': '약간', 'unit': '', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '참치는 체에 걸러 기름을 뺀다. 김치는 잘게 썰고, 대파는 송송 썬다.', 'durationSeconds': 120},
        {'stepNumber': 2, 'phase': 'heat', 'description': '팬에 기름을 두르고 센 불에 올린다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '김치를 볶아 수분을 날리고, 참치를 넣어 함께 30초 볶는다.', 'durationSeconds': 120},
        {'stepNumber': 4, 'phase': 'main', 'description': '밥을 넣고 주걱으로 밥알을 풀어가며 강불에서 고루 볶는다.', 'durationSeconds': 120, 'tip': '밥이 뭉치지 않게 처음부터 강불을 유지한다'},
        {'stepNumber': 5, 'phase': 'season', 'description': '간장 1큰술 또는 고추장을 팬 가장자리에 둘러 넣고 섞는다.', 'durationSeconds': 30},
        {'stepNumber': 6, 'phase': 'finish', 'description': '불을 끄고 참기름과 대파, 통깨를 넣어 섞는다.', 'durationSeconds': 20},
        {'stepNumber': 7, 'phase': 'plate', 'description': '달걀 후라이를 얹어 그릇에 담아 낸다.'},
      ],
      'tags': ['한식', '볶음밥', '참치', '김치', '간편'],
      'flavorProfile': {'umami': 4, 'sweet': 0, 'sour': 1, 'salty': 3, 'spicy': 2},
      'sources': [],
    },

    '카레라이스': {
      'id': 'srv_curry_rice_v1',
      'title': '카레라이스',
      'description': '채소 듬뿍 집밥 카레',
      'recipeType': 'main',
      'servings': 2,
      'cookingTimeMinutes': 35,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '카레 루', 'amount': '4', 'unit': '조각', 'isOptional': false},
        {'name': '돼지고기 또는 닭고기', 'amount': '200', 'unit': 'g', 'isOptional': false},
        {'name': '감자', 'amount': '1', 'unit': '개', 'isOptional': false},
        {'name': '당근', 'amount': '1/2', 'unit': '개', 'isOptional': false},
        {'name': '양파', 'amount': '1', 'unit': '개', 'isOptional': false},
        {'name': '물', 'amount': '700', 'unit': 'ml', 'isOptional': false},
        {'name': '식용유', 'amount': '1', 'unit': '큰술', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '고기와 채소는 한입 크기로 깍둑 썬다. 양파는 굵게 썬다.', 'durationSeconds': 300},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 식용유를 두르고 중강불에 올린다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '고기를 넣고 겉면이 익을 때까지 볶은 뒤 양파를 넣어 투명해질 때까지 볶는다.', 'durationSeconds': 300},
        {'stepNumber': 4, 'phase': 'main', 'description': '감자, 당근을 넣고 물 700ml를 붓고 센 불에서 끓인다. 거품을 걷어내고 중불로 줄여 15분 끓인다.', 'durationSeconds': 900},
        {'stepNumber': 5, 'phase': 'season', 'description': '불을 끄고 카레 루를 넣어 잘 녹인다.', 'durationSeconds': 120, 'tip': '불을 끄고 넣어야 카레 루가 뭉치지 않는다'},
        {'stepNumber': 6, 'phase': 'finish', 'description': '다시 약불에서 5분 저어가며 끓여 농도를 맞춘다.', 'durationSeconds': 300},
        {'stepNumber': 7, 'phase': 'plate', 'description': '밥 위에 카레를 듬뿍 담아 낸다.'},
      ],
      'tags': ['카레', '간편', '채소', '든든', '밥'],
      'flavorProfile': {'umami': 3, 'sweet': 2, 'sour': 0, 'salty': 2, 'spicy': 2},
      'sources': [],
    },

    '라볶이': {
      'id': 'srv_rabokki_v1',
      'title': '라볶이',
      'description': '라면 떡볶이 합체 별미',
      'recipeType': 'main',
      'servings': 2,
      'cookingTimeMinutes': 15,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '라면', 'amount': '1', 'unit': '개', 'isOptional': false},
        {'name': '떡볶이 떡', 'amount': '200', 'unit': 'g', 'isOptional': false},
        {'name': '고추장', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '간장', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '대파', 'amount': '1/2', 'unit': '대', 'isOptional': false},
        {'name': '물', 'amount': '500', 'unit': 'ml', 'isOptional': false},
        {'name': '어묵', 'amount': '100', 'unit': 'g', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '떡은 찬물에 10분 불리고, 대파는 어슷 썰고, 어묵은 먹기 좋게 썬다.', 'durationSeconds': 600},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 물 500ml를 붓고 고추장, 설탕, 간장, 라면 스프를 넣어 센 불에서 끓인다.', 'durationSeconds': 120},
        {'stepNumber': 3, 'phase': 'base', 'description': '끓어오르면 떡과 어묵을 넣는다.', 'durationSeconds': 60},
        {'stepNumber': 4, 'phase': 'main', 'description': '떡이 부드러워질 때까지 5분 끓인다.', 'durationSeconds': 300},
        {'stepNumber': 5, 'phase': 'season', 'description': '라면 면을 넣어 2분 끓이며 간을 본다.', 'durationSeconds': 120},
        {'stepNumber': 6, 'phase': 'finish', 'description': '대파를 올리고 불을 줄여 마무리한다.', 'durationSeconds': 30},
        {'stepNumber': 7, 'phase': 'plate', 'description': '냄비째 또는 그릇에 담아 낸다.', 'tip': '국물이 너무 졸면 물을 조금 추가한다'},
      ],
      'tags': ['분식', '라면', '떡볶이', '매콤', '간식'],
      'flavorProfile': {'umami': 3, 'sweet': 2, 'sour': 0, 'salty': 3, 'spicy': 4},
      'sources': [],
    },

    '갈비찜': {
      'id': 'srv_galbi_jjim_v1',
      'title': '갈비찜',
      'description': '명절 단골 감칠맛 찜',
      'recipeType': 'main',
      'servings': 2,
      'cookingTimeMinutes': 90,
      'difficulty': 'hard',
      'ingredients': [
        {'name': '소갈비', 'amount': '500', 'unit': 'g', 'isOptional': false},
        {'name': '간장', 'amount': '4', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '배즙', 'amount': '4', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '무', 'amount': '150', 'unit': 'g', 'isOptional': false},
        {'name': '당근', 'amount': '1/2', 'unit': '개', 'isOptional': false},
        {'name': '표고버섯', 'amount': '3', 'unit': '개', 'isOptional': true},
        {'name': '물', 'amount': '300', 'unit': 'ml', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '갈비는 찬물에 1~2시간 담가 핏물 제거. 무·당근은 먹기 좋게 깍둑 썬다.', 'durationSeconds': 3600, 'tip': '핏물 제거를 충분히 해야 잡내가 없다'},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 갈비를 넣고 잠길 만큼 물을 부어 10분 삶은 뒤 헹군다.', 'durationSeconds': 600},
        {'stepNumber': 3, 'phase': 'base', 'description': '간장, 설탕, 배즙, 마늘, 참기름을 섞어 양념을 만들고 삶은 갈비에 버무린다.', 'durationSeconds': 180},
        {'stepNumber': 4, 'phase': 'main', 'description': '냄비에 갈비와 물 300ml를 넣고 센 불에서 끓인다. 끓으면 중불로 30분 뭉근하게 익힌다.', 'durationSeconds': 1800},
        {'stepNumber': 5, 'phase': 'season', 'description': '무, 당근, 버섯을 넣고 20분 더 조린다. 간을 보고 조절한다.', 'durationSeconds': 1200},
        {'stepNumber': 6, 'phase': 'finish', 'description': '국물이 자작해질 때까지 조린다. 참기름을 한 방울 두른다.', 'durationSeconds': 600},
        {'stepNumber': 7, 'phase': 'plate', 'description': '그릇에 담고 잣이나 달걀지단을 올려 고급스럽게 낸다.'},
      ],
      'tags': ['한식', '갈비', '명절', '찜', '든든'],
      'flavorProfile': {'umami': 5, 'sweet': 3, 'sour': 0, 'salty': 3, 'spicy': 0},
      'scienceNote': '배즙의 단백질 분해 효소(프로테아제)가 고기 단백질을 분해해 갈비를 부드럽게 만든다.',
      'sources': [],
    },

    // ─────────────────────────────────────────────────────────────
    // 반찬 (Side dishes)
    // ─────────────────────────────────────────────────────────────
    '감자조림': {
      'id': 'srv_gamja_jorim_v1',
      'title': '감자조림',
      'description': '짭쪼름 달콤 감자반찬',
      'recipeType': 'side',
      'servings': 2,
      'cookingTimeMinutes': 25,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '감자', 'amount': '2', 'unit': '개 (중)', 'isOptional': false},
        {'name': '간장', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '물엿', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '0.5', 'unit': '작은술', 'isOptional': false},
        {'name': '물', 'amount': '200', 'unit': 'ml', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '통깨', 'amount': '1', 'unit': '작은술', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '감자는 2cm 크기로 깍둑 썰어 찬물에 10분 담가 전분을 뺀다.', 'durationSeconds': 600, 'tip': '전분을 빼면 조릴 때 뭉치지 않는다'},
        {'stepNumber': 2, 'phase': 'heat', 'description': '팬에 식용유를 두르고 감자를 중강불에서 겉면이 살짝 노릇해질 때까지 볶는다.', 'durationSeconds': 180},
        {'stepNumber': 3, 'phase': 'base', 'description': '간장, 설탕, 물엿, 마늘, 물을 섞어 양념을 만들어 감자에 붓는다.', 'durationSeconds': 60},
        {'stepNumber': 4, 'phase': 'main', 'description': '중불에서 10분 끓이며 감자가 익을 때까지 조린다.', 'durationSeconds': 600},
        {'stepNumber': 5, 'phase': 'season', 'description': '국물이 반으로 줄면 간을 보고 약불로 낮춰 5분 더 졸인다.', 'durationSeconds': 300},
        {'stepNumber': 6, 'phase': 'finish', 'description': '참기름을 넣고 팬을 흔들어 고루 코팅한다.', 'durationSeconds': 30},
        {'stepNumber': 7, 'phase': 'plate', 'description': '통깨를 뿌려 반찬 그릇에 담아 낸다.'},
      ],
      'tags': ['반찬', '감자', '조림', '짭쪼름', '달콤'],
      'flavorProfile': {'umami': 2, 'sweet': 3, 'sour': 0, 'salty': 3, 'spicy': 0},
      'sources': [],
    },

    '계란말이': {
      'id': 'srv_gyeran_mari_v1',
      'title': '계란말이',
      'description': '아침 도시락 단골 메뉴',
      'recipeType': 'side',
      'servings': 2,
      'cookingTimeMinutes': 15,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '달걀', 'amount': '4', 'unit': '개', 'isOptional': false},
        {'name': '대파', 'amount': '1/4', 'unit': '대', 'isOptional': false},
        {'name': '당근', 'amount': '1/8', 'unit': '개', 'isOptional': true},
        {'name': '소금', 'amount': '1/4', 'unit': '작은술', 'isOptional': false},
        {'name': '식용유', 'amount': '1', 'unit': '큰술', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '달걀을 볼에 깨 넣고 소금을 넣어 풀어준다. 대파, 당근은 잘게 다진다.', 'durationSeconds': 120},
        {'stepNumber': 2, 'phase': 'heat', 'description': '직사각형 팬(없으면 일반 팬)에 기름을 두르고 키친타월로 얇게 펴 약중불에 올린다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '달걀물의 1/3을 팬에 붓고 다진 채소를 고루 뿌린다.', 'durationSeconds': 60},
        {'stepNumber': 4, 'phase': 'main', 'description': '반숙 상태에서 팬 한쪽 끝부터 조심스럽게 말아 반대편으로 굴린다.', 'durationSeconds': 120, 'tip': '젓가락이나 주걱으로 살살 말아야 터지지 않는다'},
        {'stepNumber': 5, 'phase': 'season', 'description': '남은 달걀물을 2회 나눠 부어가며 같은 방법으로 두껍게 말아간다.', 'durationSeconds': 180},
        {'stepNumber': 6, 'phase': 'finish', 'description': '김발이나 랩으로 모양을 잡으며 1분 식힌다.', 'durationSeconds': 60, 'tip': '김발로 모양을 잡으면 예쁜 사각형이 된다'},
        {'stepNumber': 7, 'phase': 'plate', 'description': '먹기 좋게 썰어 도시락 반찬으로 담는다.'},
      ],
      'tags': ['반찬', '달걀', '도시락', '아침', '간단'],
      'flavorProfile': {'umami': 3, 'sweet': 0, 'sour': 0, 'salty': 2, 'spicy': 0},
      'sources': [],
    },

    '두부조림': {
      'id': 'srv_dubu_jorim_v1',
      'title': '두부조림',
      'description': '바삭한 두부에 간장양념',
      'recipeType': 'side',
      'servings': 2,
      'cookingTimeMinutes': 20,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '두부', 'amount': '1', 'unit': '모 (300g)', 'isOptional': false},
        {'name': '간장', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '고춧가루', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '0.5', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '0.5', 'unit': '작은술', 'isOptional': false},
        {'name': '대파', 'amount': '1/4', 'unit': '대', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '식용유', 'amount': '2', 'unit': '큰술', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '두부를 1.5cm 두께로 썰고 키친타월로 수분을 제거한다. 대파는 송송 썬다.', 'durationSeconds': 120, 'tip': '수분을 잘 제거해야 바삭하게 부쳐진다'},
        {'stepNumber': 2, 'phase': 'heat', 'description': '팬에 식용유를 넉넉히 두르고 중강불에 올린다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '두부를 넣고 양면이 노릇노릇해질 때까지 굽는다. (각 면 3~4분)', 'durationSeconds': 420, 'tip': '움직이지 않고 그대로 두어야 바삭해진다'},
        {'stepNumber': 4, 'phase': 'main', 'description': '간장, 고춧가루, 설탕, 마늘을 섞어 양념을 두부 위에 고루 끼얹는다.', 'durationSeconds': 60},
        {'stepNumber': 5, 'phase': 'season', 'description': '중불에서 양념이 두부에 배도록 1분 더 조린다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '대파를 뿌리고 참기름을 둘러 불을 끈다.', 'durationSeconds': 20},
        {'stepNumber': 7, 'phase': 'plate', 'description': '반찬 그릇에 담아 따뜻할 때 낸다.'},
      ],
      'tags': ['반찬', '두부', '조림', '간장', '든든'],
      'flavorProfile': {'umami': 3, 'sweet': 1, 'sour': 0, 'salty': 3, 'spicy': 2},
      'sources': [],
    },

    '시금치나물': {
      'id': 'srv_sigeumchi_namul_v1',
      'title': '시금치나물',
      'description': '참기름 향 솔솔 무침',
      'recipeType': 'side',
      'servings': 2,
      'cookingTimeMinutes': 10,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '시금치', 'amount': '200', 'unit': 'g', 'isOptional': false},
        {'name': '국간장', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '0.5', 'unit': '작은술', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '통깨', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '소금', 'amount': '약간', 'unit': '', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '시금치는 뿌리를 제거하고 깨끗이 씻는다.', 'durationSeconds': 120},
        {'stepNumber': 2, 'phase': 'heat', 'description': '끓는 물에 소금 한 꼬집을 넣고 시금치를 30~40초 데친다.', 'durationSeconds': 240, 'tip': '너무 오래 데치면 색이 변하고 영양소가 파괴된다'},
        {'stepNumber': 3, 'phase': 'base', 'description': '데친 시금치를 찬물에 즉시 헹궈 물기를 꼭 짠다.', 'durationSeconds': 120},
        {'stepNumber': 4, 'phase': 'main', 'description': '시금치를 먹기 좋게 3~4cm 길이로 자른다.', 'durationSeconds': 60},
        {'stepNumber': 5, 'phase': 'season', 'description': '국간장, 다진 마늘을 넣고 손으로 조물조물 무친다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '참기름과 통깨를 넣어 한 번 더 무친다.', 'durationSeconds': 30},
        {'stepNumber': 7, 'phase': 'plate', 'description': '반찬 그릇에 소복이 담아 낸다.'},
      ],
      'tags': ['반찬', '나물', '시금치', '무침', '건강'],
      'flavorProfile': {'umami': 2, 'sweet': 0, 'sour': 0, 'salty': 2, 'spicy': 0},
      'sources': [],
    },

    '오이무침': {
      'id': 'srv_oi_muchim_v1',
      'title': '오이무침',
      'description': '아삭하고 시원한 여름반찬',
      'recipeType': 'side',
      'servings': 2,
      'cookingTimeMinutes': 10,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '오이', 'amount': '2', 'unit': '개', 'isOptional': false},
        {'name': '소금', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '고춧가루', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '식초', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '0.5', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '0.5', 'unit': '작은술', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '통깨', 'amount': '1', 'unit': '작은술', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '오이는 0.3cm 두께로 어슷 썰어 소금에 10분 절인다.', 'durationSeconds': 600, 'tip': '소금에 절이면 오이 특유의 쓴맛이 빠진다'},
        {'stepNumber': 2, 'phase': 'heat', 'description': '(가열 없음) 절인 오이를 찬물에 헹궈 물기를 꼭 짠다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '고춧가루, 식초, 설탕, 마늘을 섞어 양념을 만든다.', 'durationSeconds': 60},
        {'stepNumber': 4, 'phase': 'main', 'description': '오이에 양념을 넣고 조물조물 무친다.', 'durationSeconds': 60},
        {'stepNumber': 5, 'phase': 'season', 'description': '간을 보고 신맛·단맛을 취향에 맞게 조절한다.', 'durationSeconds': 30},
        {'stepNumber': 6, 'phase': 'finish', 'description': '참기름과 통깨를 넣어 마무리한다.', 'durationSeconds': 20},
        {'stepNumber': 7, 'phase': 'plate', 'description': '차갑게 식혀 낸다.'},
      ],
      'tags': ['반찬', '오이', '무침', '상큼', '여름'],
      'flavorProfile': {'umami': 1, 'sweet': 1, 'sour': 3, 'salty': 2, 'spicy': 2},
      'sources': [],
    },

    '어묵볶음': {
      'id': 'srv_eomuk_bokkeum_v1',
      'title': '어묵볶음',
      'description': '달달짭짤 국민 반찬',
      'recipeType': 'side',
      'servings': 2,
      'cookingTimeMinutes': 15,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '어묵 (판)', 'amount': '200', 'unit': 'g', 'isOptional': false},
        {'name': '간장', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '물엿', 'amount': '0.5', 'unit': '큰술', 'isOptional': true},
        {'name': '다진 마늘', 'amount': '0.5', 'unit': '작은술', 'isOptional': false},
        {'name': '대파', 'amount': '1/3', 'unit': '대', 'isOptional': false},
        {'name': '고추', 'amount': '1', 'unit': '개', 'isOptional': true},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '어묵은 끓는 물에 데쳐 기름을 제거하고 먹기 좋게 썬다. 대파, 고추는 어슷 썬다.', 'durationSeconds': 180, 'tip': '어묵을 데치면 기름기와 잡내가 줄어든다'},
        {'stepNumber': 2, 'phase': 'heat', 'description': '팬에 식용유를 두르고 중강불에 올린다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '어묵을 넣어 1분간 볶는다.', 'durationSeconds': 60},
        {'stepNumber': 4, 'phase': 'main', 'description': '간장, 설탕, 마늘, 물엿을 넣고 중불에서 2분 볶아 양념이 배게 한다.', 'durationSeconds': 120},
        {'stepNumber': 5, 'phase': 'season', 'description': '대파와 고추를 넣고 1분 더 볶는다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '참기름을 두르고 불을 끈다.', 'durationSeconds': 20},
        {'stepNumber': 7, 'phase': 'plate', 'description': '통깨를 뿌려 반찬 그릇에 담는다.'},
      ],
      'tags': ['반찬', '어묵', '볶음', '달달', '간편'],
      'flavorProfile': {'umami': 3, 'sweet': 3, 'sour': 0, 'salty': 3, 'spicy': 1},
      'sources': [],
    },

    '겉절이': {
      'id': 'srv_geotjeori_v1',
      'title': '겉절이',
      'description': '갓 버무린 생배추김치',
      'recipeType': 'side',
      'servings': 2,
      'cookingTimeMinutes': 10,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '배추', 'amount': '1/4', 'unit': '통', 'isOptional': false},
        {'name': '소금', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '고춧가루', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '다진 마늘', 'amount': '0.5', 'unit': '작은술', 'isOptional': false},
        {'name': '새우젓', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '0.5', 'unit': '큰술', 'isOptional': false},
        {'name': '참기름', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '통깨', 'amount': '1', 'unit': '작은술', 'isOptional': true},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '배추를 한입 크기로 찢어 소금을 뿌리고 10분 절인다.', 'durationSeconds': 600},
        {'stepNumber': 2, 'phase': 'heat', 'description': '(가열 없음) 절인 배추를 찬물에 한번 헹궈 물기를 꼭 짜낸다.', 'durationSeconds': 60},
        {'stepNumber': 3, 'phase': 'base', 'description': '고춧가루, 마늘, 새우젓, 설탕을 섞어 양념을 만든다.', 'durationSeconds': 60},
        {'stepNumber': 4, 'phase': 'main', 'description': '배추에 양념을 넣고 손으로 조물조물 무친다.', 'durationSeconds': 60, 'tip': '장갑을 끼면 손에 색이 배지 않는다'},
        {'stepNumber': 5, 'phase': 'season', 'description': '간을 보고 짠맛이 부족하면 새우젓, 단맛은 설탕으로 조절한다.', 'durationSeconds': 30},
        {'stepNumber': 6, 'phase': 'finish', 'description': '참기름과 통깨를 넣어 마무리한다.', 'durationSeconds': 20},
        {'stepNumber': 7, 'phase': 'plate', 'description': '바로 담아 신선하게 낸다.', 'tip': '겉절이는 만든 직후 먹어야 아삭하고 맛있다'},
      ],
      'tags': ['반찬', '배추', '겉절이', '상큼', '신선'],
      'flavorProfile': {'umami': 2, 'sweet': 1, 'sour': 1, 'salty': 2, 'spicy': 3},
      'sources': [],
    },

    // ─────────────────────────────────────────────────────────────
    // 간식 (Snack)
    // ─────────────────────────────────────────────────────────────
    '떡볶이': {
      'id': 'srv_tteokbokki_v1',
      'title': '떡볶이',
      'description': '매콤달콤 길거리 간식',
      'recipeType': 'snack',
      'servings': 2,
      'cookingTimeMinutes': 20,
      'difficulty': 'easy',
      'ingredients': [
        {'name': '떡볶이 떡', 'amount': '300', 'unit': 'g', 'isOptional': false},
        {'name': '어묵', 'amount': '100', 'unit': 'g', 'isOptional': false},
        {'name': '고추장', 'amount': '2', 'unit': '큰술', 'isOptional': false},
        {'name': '고춧가루', 'amount': '1', 'unit': '큰술', 'isOptional': false},
        {'name': '설탕', 'amount': '1.5', 'unit': '큰술', 'isOptional': false},
        {'name': '간장', 'amount': '1', 'unit': '작은술', 'isOptional': false},
        {'name': '다시마 물 또는 물', 'amount': '500', 'unit': 'ml', 'isOptional': false},
        {'name': '대파', 'amount': '1/3', 'unit': '대', 'isOptional': false},
      ],
      'steps': [
        {'stepNumber': 1, 'phase': 'prep', 'description': '떡은 찬물에 10분 담가 부드럽게 만들고, 어묵은 먹기 좋게 썬다. 대파는 어슷 썬다.', 'durationSeconds': 600},
        {'stepNumber': 2, 'phase': 'heat', 'description': '냄비에 물(또는 다시마 물)을 넣고 센 불에 올린다.', 'durationSeconds': 120, 'tip': '다시마 물을 쓰면 더 깊은 맛이 난다'},
        {'stepNumber': 3, 'phase': 'base', 'description': '고추장, 고춧가루, 설탕, 간장을 넣고 잘 풀어 끓인다.', 'durationSeconds': 60},
        {'stepNumber': 4, 'phase': 'main', 'description': '떡과 어묵을 넣고 중강불에서 떡이 부드러워질 때까지 8~10분 끓인다.', 'durationSeconds': 600},
        {'stepNumber': 5, 'phase': 'season', 'description': '간을 보고 달면 고추장, 짜면 물을 추가한다.', 'durationSeconds': 60},
        {'stepNumber': 6, 'phase': 'finish', 'description': '대파를 넣고 1분 더 끓인다. 국물이 걸쭉해지면 완성.', 'durationSeconds': 60},
        {'stepNumber': 7, 'phase': 'plate', 'description': '그릇에 담아 삶은 달걀과 함께 낸다.'},
      ],
      'tags': ['분식', '떡볶이', '매콤', '달콤', '간식'],
      'flavorProfile': {'umami': 2, 'sweet': 3, 'sour': 0, 'salty': 2, 'spicy': 4},
      'sources': [],
    },
  };
}
